/*
 * Pay OpenAPI Documentations
 *
 * This is a pay service api server.
 *
 * API version: 1.0
 * Contact: support@openweb3.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CryptoCurrency struct for CryptoCurrency
type CryptoCurrency struct {
	// Currency code
	Code string `json:"code"`
	// Decimals
	Decimals int32 `json:"decimals"`
	// Max Withdraw Amount (Integer)
	MaxWithdrawAmount string `json:"maxWithdrawAmount"`
	// Min Deposit Amount (Integer)
	MinDepositAmount string `json:"minDepositAmount"`
	// Min Withdraw Amount (Integer)
	MinWithdrawAmount string `json:"minWithdrawAmount"`
	// Currency name
	Name string `json:"name"`
	// Networks
	Networks []CryptoCurrencyNetwork `json:"networks"`
	// Precision
	Precision int32 `json:"precision"`
}

// NewCryptoCurrency instantiates a new CryptoCurrency object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCryptoCurrency(code string, decimals int32, maxWithdrawAmount string, minDepositAmount string, minWithdrawAmount string, name string, networks []CryptoCurrencyNetwork, precision int32) *CryptoCurrency {
	this := CryptoCurrency{}
	this.Code = code
	this.Decimals = decimals
	this.MaxWithdrawAmount = maxWithdrawAmount
	this.MinDepositAmount = minDepositAmount
	this.MinWithdrawAmount = minWithdrawAmount
	this.Name = name
	this.Networks = networks
	this.Precision = precision
	return &this
}

// NewCryptoCurrencyWithDefaults instantiates a new CryptoCurrency object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCryptoCurrencyWithDefaults() *CryptoCurrency {
	this := CryptoCurrency{}
	return &this
}

// GetCode returns the Code field value
func (o *CryptoCurrency) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *CryptoCurrency) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *CryptoCurrency) SetCode(v string) {
	o.Code = v
}

// GetDecimals returns the Decimals field value
func (o *CryptoCurrency) GetDecimals() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Decimals
}

// GetDecimalsOk returns a tuple with the Decimals field value
// and a boolean to check if the value has been set.
func (o *CryptoCurrency) GetDecimalsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decimals, true
}

// SetDecimals sets field value
func (o *CryptoCurrency) SetDecimals(v int32) {
	o.Decimals = v
}

// GetMaxWithdrawAmount returns the MaxWithdrawAmount field value
func (o *CryptoCurrency) GetMaxWithdrawAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MaxWithdrawAmount
}

// GetMaxWithdrawAmountOk returns a tuple with the MaxWithdrawAmount field value
// and a boolean to check if the value has been set.
func (o *CryptoCurrency) GetMaxWithdrawAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxWithdrawAmount, true
}

// SetMaxWithdrawAmount sets field value
func (o *CryptoCurrency) SetMaxWithdrawAmount(v string) {
	o.MaxWithdrawAmount = v
}

// GetMinDepositAmount returns the MinDepositAmount field value
func (o *CryptoCurrency) GetMinDepositAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MinDepositAmount
}

// GetMinDepositAmountOk returns a tuple with the MinDepositAmount field value
// and a boolean to check if the value has been set.
func (o *CryptoCurrency) GetMinDepositAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinDepositAmount, true
}

// SetMinDepositAmount sets field value
func (o *CryptoCurrency) SetMinDepositAmount(v string) {
	o.MinDepositAmount = v
}

// GetMinWithdrawAmount returns the MinWithdrawAmount field value
func (o *CryptoCurrency) GetMinWithdrawAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MinWithdrawAmount
}

// GetMinWithdrawAmountOk returns a tuple with the MinWithdrawAmount field value
// and a boolean to check if the value has been set.
func (o *CryptoCurrency) GetMinWithdrawAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinWithdrawAmount, true
}

// SetMinWithdrawAmount sets field value
func (o *CryptoCurrency) SetMinWithdrawAmount(v string) {
	o.MinWithdrawAmount = v
}

// GetName returns the Name field value
func (o *CryptoCurrency) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CryptoCurrency) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CryptoCurrency) SetName(v string) {
	o.Name = v
}

// GetNetworks returns the Networks field value
func (o *CryptoCurrency) GetNetworks() []CryptoCurrencyNetwork {
	if o == nil {
		var ret []CryptoCurrencyNetwork
		return ret
	}

	return o.Networks
}

// GetNetworksOk returns a tuple with the Networks field value
// and a boolean to check if the value has been set.
func (o *CryptoCurrency) GetNetworksOk() (*[]CryptoCurrencyNetwork, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Networks, true
}

// SetNetworks sets field value
func (o *CryptoCurrency) SetNetworks(v []CryptoCurrencyNetwork) {
	o.Networks = v
}

// GetPrecision returns the Precision field value
func (o *CryptoCurrency) GetPrecision() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Precision
}

// GetPrecisionOk returns a tuple with the Precision field value
// and a boolean to check if the value has been set.
func (o *CryptoCurrency) GetPrecisionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Precision, true
}

// SetPrecision sets field value
func (o *CryptoCurrency) SetPrecision(v int32) {
	o.Precision = v
}

func (o CryptoCurrency) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["code"] = o.Code
	}
	if true {
		toSerialize["decimals"] = o.Decimals
	}
	if true {
		toSerialize["maxWithdrawAmount"] = o.MaxWithdrawAmount
	}
	if true {
		toSerialize["minDepositAmount"] = o.MinDepositAmount
	}
	if true {
		toSerialize["minWithdrawAmount"] = o.MinWithdrawAmount
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["networks"] = o.Networks
	}
	if true {
		toSerialize["precision"] = o.Precision
	}
	return json.Marshal(toSerialize)
}

type NullableCryptoCurrency struct {
	value *CryptoCurrency
	isSet bool
}

func (v NullableCryptoCurrency) Get() *CryptoCurrency {
	return v.value
}

func (v *NullableCryptoCurrency) Set(val *CryptoCurrency) {
	v.value = val
	v.isSet = true
}

func (v NullableCryptoCurrency) IsSet() bool {
	return v.isSet
}

func (v *NullableCryptoCurrency) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCryptoCurrency(val *CryptoCurrency) *NullableCryptoCurrency {
	return &NullableCryptoCurrency{value: val, isSet: true}
}

func (v NullableCryptoCurrency) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCryptoCurrency) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
