/*
 * Pay OpenAPI Documentations
 *
 * This is a pay service api server.
 *
 * API version: 1.0
 * Contact: support@openweb3.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreatePayout struct for CreatePayout
type CreatePayout struct {
	// Amount (Integer)
	Amount *string `json:"amount,omitempty"`
	// Currency Code
	Currency *string `json:"currency,omitempty"`
	// Currency Network
	Network *string `json:"network,omitempty"`
	// Payout notes
	Note *string `json:"note,omitempty"`
	// To Address
	ToAddress *string `json:"toAddress,omitempty"`
	// User ID
	UserId *string `json:"userId,omitempty"`
}

// NewCreatePayout instantiates a new CreatePayout object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePayout() *CreatePayout {
	this := CreatePayout{}
	return &this
}

// NewCreatePayoutWithDefaults instantiates a new CreatePayout object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePayoutWithDefaults() *CreatePayout {
	this := CreatePayout{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *CreatePayout) GetAmount() string {
	if o == nil || o.Amount == nil {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePayout) GetAmountOk() (*string, bool) {
	if o == nil || o.Amount == nil {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *CreatePayout) HasAmount() bool {
	if o != nil && o.Amount != nil {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *CreatePayout) SetAmount(v string) {
	o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *CreatePayout) GetCurrency() string {
	if o == nil || o.Currency == nil {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePayout) GetCurrencyOk() (*string, bool) {
	if o == nil || o.Currency == nil {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *CreatePayout) HasCurrency() bool {
	if o != nil && o.Currency != nil {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *CreatePayout) SetCurrency(v string) {
	o.Currency = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *CreatePayout) GetNetwork() string {
	if o == nil || o.Network == nil {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePayout) GetNetworkOk() (*string, bool) {
	if o == nil || o.Network == nil {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *CreatePayout) HasNetwork() bool {
	if o != nil && o.Network != nil {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *CreatePayout) SetNetwork(v string) {
	o.Network = &v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *CreatePayout) GetNote() string {
	if o == nil || o.Note == nil {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePayout) GetNoteOk() (*string, bool) {
	if o == nil || o.Note == nil {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *CreatePayout) HasNote() bool {
	if o != nil && o.Note != nil {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *CreatePayout) SetNote(v string) {
	o.Note = &v
}

// GetToAddress returns the ToAddress field value if set, zero value otherwise.
func (o *CreatePayout) GetToAddress() string {
	if o == nil || o.ToAddress == nil {
		var ret string
		return ret
	}
	return *o.ToAddress
}

// GetToAddressOk returns a tuple with the ToAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePayout) GetToAddressOk() (*string, bool) {
	if o == nil || o.ToAddress == nil {
		return nil, false
	}
	return o.ToAddress, true
}

// HasToAddress returns a boolean if a field has been set.
func (o *CreatePayout) HasToAddress() bool {
	if o != nil && o.ToAddress != nil {
		return true
	}

	return false
}

// SetToAddress gets a reference to the given string and assigns it to the ToAddress field.
func (o *CreatePayout) SetToAddress(v string) {
	o.ToAddress = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *CreatePayout) GetUserId() string {
	if o == nil || o.UserId == nil {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePayout) GetUserIdOk() (*string, bool) {
	if o == nil || o.UserId == nil {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *CreatePayout) HasUserId() bool {
	if o != nil && o.UserId != nil {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *CreatePayout) SetUserId(v string) {
	o.UserId = &v
}

func (o CreatePayout) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Amount != nil {
		toSerialize["amount"] = o.Amount
	}
	if o.Currency != nil {
		toSerialize["currency"] = o.Currency
	}
	if o.Network != nil {
		toSerialize["network"] = o.Network
	}
	if o.Note != nil {
		toSerialize["note"] = o.Note
	}
	if o.ToAddress != nil {
		toSerialize["toAddress"] = o.ToAddress
	}
	if o.UserId != nil {
		toSerialize["userId"] = o.UserId
	}
	return json.Marshal(toSerialize)
}

type NullableCreatePayout struct {
	value *CreatePayout
	isSet bool
}

func (v NullableCreatePayout) Get() *CreatePayout {
	return v.value
}

func (v *NullableCreatePayout) Set(val *CreatePayout) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePayout) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePayout) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePayout(val *CreatePayout) *NullableCreatePayout {
	return &NullableCreatePayout{value: val, isSet: true}
}

func (v NullableCreatePayout) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePayout) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


