/*
 * Pay OpenAPI Documentations
 *
 * This is a pay service api server.
 *
 * API version: 1.0
 * Contact: support@openweb3.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CryptoCurrency struct for CryptoCurrency
type CryptoCurrency struct {
	// Currency code
	Code *string `json:"code,omitempty"`
	// Decimals
	Decimals *int32 `json:"decimals,omitempty"`
	// Max Withdraw Amount (Integer)
	MaxWithdrawAmount *string `json:"maxWithdrawAmount,omitempty"`
	// Min Deposit Amount (Integer)
	MinDepositAmount *string `json:"minDepositAmount,omitempty"`
	// Min Withdraw Amount (Integer)
	MinWithdrawAmount *string `json:"minWithdrawAmount,omitempty"`
	// Currency name
	Name *string `json:"name,omitempty"`
	// Networks
	Networks *[]CryptoCurrencyNetwork `json:"networks,omitempty"`
	// Precision
	Precision *int32 `json:"precision,omitempty"`
}

// NewCryptoCurrency instantiates a new CryptoCurrency object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCryptoCurrency() *CryptoCurrency {
	this := CryptoCurrency{}
	return &this
}

// NewCryptoCurrencyWithDefaults instantiates a new CryptoCurrency object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCryptoCurrencyWithDefaults() *CryptoCurrency {
	this := CryptoCurrency{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CryptoCurrency) GetCode() string {
	if o == nil || o.Code == nil {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoCurrency) GetCodeOk() (*string, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CryptoCurrency) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *CryptoCurrency) SetCode(v string) {
	o.Code = &v
}

// GetDecimals returns the Decimals field value if set, zero value otherwise.
func (o *CryptoCurrency) GetDecimals() int32 {
	if o == nil || o.Decimals == nil {
		var ret int32
		return ret
	}
	return *o.Decimals
}

// GetDecimalsOk returns a tuple with the Decimals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoCurrency) GetDecimalsOk() (*int32, bool) {
	if o == nil || o.Decimals == nil {
		return nil, false
	}
	return o.Decimals, true
}

// HasDecimals returns a boolean if a field has been set.
func (o *CryptoCurrency) HasDecimals() bool {
	if o != nil && o.Decimals != nil {
		return true
	}

	return false
}

// SetDecimals gets a reference to the given int32 and assigns it to the Decimals field.
func (o *CryptoCurrency) SetDecimals(v int32) {
	o.Decimals = &v
}

// GetMaxWithdrawAmount returns the MaxWithdrawAmount field value if set, zero value otherwise.
func (o *CryptoCurrency) GetMaxWithdrawAmount() string {
	if o == nil || o.MaxWithdrawAmount == nil {
		var ret string
		return ret
	}
	return *o.MaxWithdrawAmount
}

// GetMaxWithdrawAmountOk returns a tuple with the MaxWithdrawAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoCurrency) GetMaxWithdrawAmountOk() (*string, bool) {
	if o == nil || o.MaxWithdrawAmount == nil {
		return nil, false
	}
	return o.MaxWithdrawAmount, true
}

// HasMaxWithdrawAmount returns a boolean if a field has been set.
func (o *CryptoCurrency) HasMaxWithdrawAmount() bool {
	if o != nil && o.MaxWithdrawAmount != nil {
		return true
	}

	return false
}

// SetMaxWithdrawAmount gets a reference to the given string and assigns it to the MaxWithdrawAmount field.
func (o *CryptoCurrency) SetMaxWithdrawAmount(v string) {
	o.MaxWithdrawAmount = &v
}

// GetMinDepositAmount returns the MinDepositAmount field value if set, zero value otherwise.
func (o *CryptoCurrency) GetMinDepositAmount() string {
	if o == nil || o.MinDepositAmount == nil {
		var ret string
		return ret
	}
	return *o.MinDepositAmount
}

// GetMinDepositAmountOk returns a tuple with the MinDepositAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoCurrency) GetMinDepositAmountOk() (*string, bool) {
	if o == nil || o.MinDepositAmount == nil {
		return nil, false
	}
	return o.MinDepositAmount, true
}

// HasMinDepositAmount returns a boolean if a field has been set.
func (o *CryptoCurrency) HasMinDepositAmount() bool {
	if o != nil && o.MinDepositAmount != nil {
		return true
	}

	return false
}

// SetMinDepositAmount gets a reference to the given string and assigns it to the MinDepositAmount field.
func (o *CryptoCurrency) SetMinDepositAmount(v string) {
	o.MinDepositAmount = &v
}

// GetMinWithdrawAmount returns the MinWithdrawAmount field value if set, zero value otherwise.
func (o *CryptoCurrency) GetMinWithdrawAmount() string {
	if o == nil || o.MinWithdrawAmount == nil {
		var ret string
		return ret
	}
	return *o.MinWithdrawAmount
}

// GetMinWithdrawAmountOk returns a tuple with the MinWithdrawAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoCurrency) GetMinWithdrawAmountOk() (*string, bool) {
	if o == nil || o.MinWithdrawAmount == nil {
		return nil, false
	}
	return o.MinWithdrawAmount, true
}

// HasMinWithdrawAmount returns a boolean if a field has been set.
func (o *CryptoCurrency) HasMinWithdrawAmount() bool {
	if o != nil && o.MinWithdrawAmount != nil {
		return true
	}

	return false
}

// SetMinWithdrawAmount gets a reference to the given string and assigns it to the MinWithdrawAmount field.
func (o *CryptoCurrency) SetMinWithdrawAmount(v string) {
	o.MinWithdrawAmount = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CryptoCurrency) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoCurrency) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CryptoCurrency) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CryptoCurrency) SetName(v string) {
	o.Name = &v
}

// GetNetworks returns the Networks field value if set, zero value otherwise.
func (o *CryptoCurrency) GetNetworks() []CryptoCurrencyNetwork {
	if o == nil || o.Networks == nil {
		var ret []CryptoCurrencyNetwork
		return ret
	}
	return *o.Networks
}

// GetNetworksOk returns a tuple with the Networks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoCurrency) GetNetworksOk() (*[]CryptoCurrencyNetwork, bool) {
	if o == nil || o.Networks == nil {
		return nil, false
	}
	return o.Networks, true
}

// HasNetworks returns a boolean if a field has been set.
func (o *CryptoCurrency) HasNetworks() bool {
	if o != nil && o.Networks != nil {
		return true
	}

	return false
}

// SetNetworks gets a reference to the given []CryptoCurrencyNetwork and assigns it to the Networks field.
func (o *CryptoCurrency) SetNetworks(v []CryptoCurrencyNetwork) {
	o.Networks = &v
}

// GetPrecision returns the Precision field value if set, zero value otherwise.
func (o *CryptoCurrency) GetPrecision() int32 {
	if o == nil || o.Precision == nil {
		var ret int32
		return ret
	}
	return *o.Precision
}

// GetPrecisionOk returns a tuple with the Precision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoCurrency) GetPrecisionOk() (*int32, bool) {
	if o == nil || o.Precision == nil {
		return nil, false
	}
	return o.Precision, true
}

// HasPrecision returns a boolean if a field has been set.
func (o *CryptoCurrency) HasPrecision() bool {
	if o != nil && o.Precision != nil {
		return true
	}

	return false
}

// SetPrecision gets a reference to the given int32 and assigns it to the Precision field.
func (o *CryptoCurrency) SetPrecision(v int32) {
	o.Precision = &v
}

func (o CryptoCurrency) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Decimals != nil {
		toSerialize["decimals"] = o.Decimals
	}
	if o.MaxWithdrawAmount != nil {
		toSerialize["maxWithdrawAmount"] = o.MaxWithdrawAmount
	}
	if o.MinDepositAmount != nil {
		toSerialize["minDepositAmount"] = o.MinDepositAmount
	}
	if o.MinWithdrawAmount != nil {
		toSerialize["minWithdrawAmount"] = o.MinWithdrawAmount
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Networks != nil {
		toSerialize["networks"] = o.Networks
	}
	if o.Precision != nil {
		toSerialize["precision"] = o.Precision
	}
	return json.Marshal(toSerialize)
}

type NullableCryptoCurrency struct {
	value *CryptoCurrency
	isSet bool
}

func (v NullableCryptoCurrency) Get() *CryptoCurrency {
	return v.value
}

func (v *NullableCryptoCurrency) Set(val *CryptoCurrency) {
	v.value = val
	v.isSet = true
}

func (v NullableCryptoCurrency) IsSet() bool {
	return v.isSet
}

func (v *NullableCryptoCurrency) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCryptoCurrency(val *CryptoCurrency) *NullableCryptoCurrency {
	return &NullableCryptoCurrency{value: val, isSet: true}
}

func (v NullableCryptoCurrency) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCryptoCurrency) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


