/*
 * Pay OpenAPI Documentations
 *
 * This is a pay service api server.
 *
 * API version: 1.0
 * Contact: support@openweb3.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// FiatCurrency struct for FiatCurrency
type FiatCurrency struct {
	// Currency Code
	Code string `json:"code"`
	// Currency Name
	Name string `json:"name"`
}

// NewFiatCurrency instantiates a new FiatCurrency object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFiatCurrency(code string, name string) *FiatCurrency {
	this := FiatCurrency{}
	this.Code = code
	this.Name = name
	return &this
}

// NewFiatCurrencyWithDefaults instantiates a new FiatCurrency object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFiatCurrencyWithDefaults() *FiatCurrency {
	this := FiatCurrency{}
	return &this
}

// GetCode returns the Code field value
func (o *FiatCurrency) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *FiatCurrency) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *FiatCurrency) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *FiatCurrency) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FiatCurrency) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FiatCurrency) SetName(v string) {
	o.Name = v
}

func (o FiatCurrency) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["code"] = o.Code
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableFiatCurrency struct {
	value *FiatCurrency
	isSet bool
}

func (v NullableFiatCurrency) Get() *FiatCurrency {
	return v.value
}

func (v *NullableFiatCurrency) Set(val *FiatCurrency) {
	v.value = val
	v.isSet = true
}

func (v NullableFiatCurrency) IsSet() bool {
	return v.isSet
}

func (v *NullableFiatCurrency) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFiatCurrency(val *FiatCurrency) *NullableFiatCurrency {
	return &NullableFiatCurrency{value: val, isSet: true}
}

func (v NullableFiatCurrency) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFiatCurrency) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
