/*
 * Pay OpenAPI Documentations
 *
 * This is a pay service api server.
 *
 * API version: 1.0
 * Contact: support@openweb3.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CryptoCurrencyNetwork struct for CryptoCurrencyNetwork
type CryptoCurrencyNetwork struct {
	// Can Deposit
	CanDeposit *bool `json:"canDeposit,omitempty"`
	// Can Transfer
	CanTransfer *bool `json:"canTransfer,omitempty"`
	// Can Withdraw
	CanWithdraw *bool `json:"canWithdraw,omitempty"`
	// Network code
	Code *string `json:"code,omitempty"`
	// Network display name
	Name *string `json:"name,omitempty"`
	// Network name
	Network *string `json:"network,omitempty"`
}

// NewCryptoCurrencyNetwork instantiates a new CryptoCurrencyNetwork object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCryptoCurrencyNetwork() *CryptoCurrencyNetwork {
	this := CryptoCurrencyNetwork{}
	return &this
}

// NewCryptoCurrencyNetworkWithDefaults instantiates a new CryptoCurrencyNetwork object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCryptoCurrencyNetworkWithDefaults() *CryptoCurrencyNetwork {
	this := CryptoCurrencyNetwork{}
	return &this
}

// GetCanDeposit returns the CanDeposit field value if set, zero value otherwise.
func (o *CryptoCurrencyNetwork) GetCanDeposit() bool {
	if o == nil || o.CanDeposit == nil {
		var ret bool
		return ret
	}
	return *o.CanDeposit
}

// GetCanDepositOk returns a tuple with the CanDeposit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoCurrencyNetwork) GetCanDepositOk() (*bool, bool) {
	if o == nil || o.CanDeposit == nil {
		return nil, false
	}
	return o.CanDeposit, true
}

// HasCanDeposit returns a boolean if a field has been set.
func (o *CryptoCurrencyNetwork) HasCanDeposit() bool {
	if o != nil && o.CanDeposit != nil {
		return true
	}

	return false
}

// SetCanDeposit gets a reference to the given bool and assigns it to the CanDeposit field.
func (o *CryptoCurrencyNetwork) SetCanDeposit(v bool) {
	o.CanDeposit = &v
}

// GetCanTransfer returns the CanTransfer field value if set, zero value otherwise.
func (o *CryptoCurrencyNetwork) GetCanTransfer() bool {
	if o == nil || o.CanTransfer == nil {
		var ret bool
		return ret
	}
	return *o.CanTransfer
}

// GetCanTransferOk returns a tuple with the CanTransfer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoCurrencyNetwork) GetCanTransferOk() (*bool, bool) {
	if o == nil || o.CanTransfer == nil {
		return nil, false
	}
	return o.CanTransfer, true
}

// HasCanTransfer returns a boolean if a field has been set.
func (o *CryptoCurrencyNetwork) HasCanTransfer() bool {
	if o != nil && o.CanTransfer != nil {
		return true
	}

	return false
}

// SetCanTransfer gets a reference to the given bool and assigns it to the CanTransfer field.
func (o *CryptoCurrencyNetwork) SetCanTransfer(v bool) {
	o.CanTransfer = &v
}

// GetCanWithdraw returns the CanWithdraw field value if set, zero value otherwise.
func (o *CryptoCurrencyNetwork) GetCanWithdraw() bool {
	if o == nil || o.CanWithdraw == nil {
		var ret bool
		return ret
	}
	return *o.CanWithdraw
}

// GetCanWithdrawOk returns a tuple with the CanWithdraw field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoCurrencyNetwork) GetCanWithdrawOk() (*bool, bool) {
	if o == nil || o.CanWithdraw == nil {
		return nil, false
	}
	return o.CanWithdraw, true
}

// HasCanWithdraw returns a boolean if a field has been set.
func (o *CryptoCurrencyNetwork) HasCanWithdraw() bool {
	if o != nil && o.CanWithdraw != nil {
		return true
	}

	return false
}

// SetCanWithdraw gets a reference to the given bool and assigns it to the CanWithdraw field.
func (o *CryptoCurrencyNetwork) SetCanWithdraw(v bool) {
	o.CanWithdraw = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CryptoCurrencyNetwork) GetCode() string {
	if o == nil || o.Code == nil {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoCurrencyNetwork) GetCodeOk() (*string, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CryptoCurrencyNetwork) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *CryptoCurrencyNetwork) SetCode(v string) {
	o.Code = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CryptoCurrencyNetwork) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoCurrencyNetwork) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CryptoCurrencyNetwork) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CryptoCurrencyNetwork) SetName(v string) {
	o.Name = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *CryptoCurrencyNetwork) GetNetwork() string {
	if o == nil || o.Network == nil {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoCurrencyNetwork) GetNetworkOk() (*string, bool) {
	if o == nil || o.Network == nil {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *CryptoCurrencyNetwork) HasNetwork() bool {
	if o != nil && o.Network != nil {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *CryptoCurrencyNetwork) SetNetwork(v string) {
	o.Network = &v
}

func (o CryptoCurrencyNetwork) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CanDeposit != nil {
		toSerialize["canDeposit"] = o.CanDeposit
	}
	if o.CanTransfer != nil {
		toSerialize["canTransfer"] = o.CanTransfer
	}
	if o.CanWithdraw != nil {
		toSerialize["canWithdraw"] = o.CanWithdraw
	}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Network != nil {
		toSerialize["network"] = o.Network
	}
	return json.Marshal(toSerialize)
}

type NullableCryptoCurrencyNetwork struct {
	value *CryptoCurrencyNetwork
	isSet bool
}

func (v NullableCryptoCurrencyNetwork) Get() *CryptoCurrencyNetwork {
	return v.value
}

func (v *NullableCryptoCurrencyNetwork) Set(val *CryptoCurrencyNetwork) {
	v.value = val
	v.isSet = true
}

func (v NullableCryptoCurrencyNetwork) IsSet() bool {
	return v.isSet
}

func (v *NullableCryptoCurrencyNetwork) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCryptoCurrencyNetwork(val *CryptoCurrencyNetwork) *NullableCryptoCurrencyNetwork {
	return &NullableCryptoCurrencyNetwork{value: val, isSet: true}
}

func (v NullableCryptoCurrencyNetwork) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCryptoCurrencyNetwork) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


