/*
 * Pay OpenAPI Documentations
 *
 * This is a pay service api server.
 *
 * API version: 1.0
 * Contact: support@openweb3.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateRefund struct for CreateRefund
type CreateRefund struct {
	// Refund amount (Integer)
	Amount *string `json:"amount,omitempty"`
	// Refund note
	Note *string `json:"note,omitempty"`
	// Payment ID
	PaymentId *string `json:"payment_id,omitempty"`
	// To Address
	ToAddress *string `json:"to_address,omitempty"`
}

// NewCreateRefund instantiates a new CreateRefund object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRefund() *CreateRefund {
	this := CreateRefund{}
	return &this
}

// NewCreateRefundWithDefaults instantiates a new CreateRefund object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRefundWithDefaults() *CreateRefund {
	this := CreateRefund{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *CreateRefund) GetAmount() string {
	if o == nil || o.Amount == nil {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRefund) GetAmountOk() (*string, bool) {
	if o == nil || o.Amount == nil {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *CreateRefund) HasAmount() bool {
	if o != nil && o.Amount != nil {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *CreateRefund) SetAmount(v string) {
	o.Amount = &v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *CreateRefund) GetNote() string {
	if o == nil || o.Note == nil {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRefund) GetNoteOk() (*string, bool) {
	if o == nil || o.Note == nil {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *CreateRefund) HasNote() bool {
	if o != nil && o.Note != nil {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *CreateRefund) SetNote(v string) {
	o.Note = &v
}

// GetPaymentId returns the PaymentId field value if set, zero value otherwise.
func (o *CreateRefund) GetPaymentId() string {
	if o == nil || o.PaymentId == nil {
		var ret string
		return ret
	}
	return *o.PaymentId
}

// GetPaymentIdOk returns a tuple with the PaymentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRefund) GetPaymentIdOk() (*string, bool) {
	if o == nil || o.PaymentId == nil {
		return nil, false
	}
	return o.PaymentId, true
}

// HasPaymentId returns a boolean if a field has been set.
func (o *CreateRefund) HasPaymentId() bool {
	if o != nil && o.PaymentId != nil {
		return true
	}

	return false
}

// SetPaymentId gets a reference to the given string and assigns it to the PaymentId field.
func (o *CreateRefund) SetPaymentId(v string) {
	o.PaymentId = &v
}

// GetToAddress returns the ToAddress field value if set, zero value otherwise.
func (o *CreateRefund) GetToAddress() string {
	if o == nil || o.ToAddress == nil {
		var ret string
		return ret
	}
	return *o.ToAddress
}

// GetToAddressOk returns a tuple with the ToAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRefund) GetToAddressOk() (*string, bool) {
	if o == nil || o.ToAddress == nil {
		return nil, false
	}
	return o.ToAddress, true
}

// HasToAddress returns a boolean if a field has been set.
func (o *CreateRefund) HasToAddress() bool {
	if o != nil && o.ToAddress != nil {
		return true
	}

	return false
}

// SetToAddress gets a reference to the given string and assigns it to the ToAddress field.
func (o *CreateRefund) SetToAddress(v string) {
	o.ToAddress = &v
}

func (o CreateRefund) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Amount != nil {
		toSerialize["amount"] = o.Amount
	}
	if o.Note != nil {
		toSerialize["note"] = o.Note
	}
	if o.PaymentId != nil {
		toSerialize["payment_id"] = o.PaymentId
	}
	if o.ToAddress != nil {
		toSerialize["to_address"] = o.ToAddress
	}
	return json.Marshal(toSerialize)
}

type NullableCreateRefund struct {
	value *CreateRefund
	isSet bool
}

func (v NullableCreateRefund) Get() *CreateRefund {
	return v.value
}

func (v *NullableCreateRefund) Set(val *CreateRefund) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRefund) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRefund) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRefund(val *CreateRefund) *NullableCreateRefund {
	return &NullableCreateRefund{value: val, isSet: true}
}

func (v NullableCreateRefund) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRefund) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


