/*
 * Pay OpenAPI Documentations
 *
 * This is a pay service api server.
 *
 * API version: 1.0
 * Contact: support@openweb3.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CursorPagePayout struct for CursorPagePayout
type CursorPagePayout struct {
	Items *[]Payout `json:"items,omitempty"`
	NextCursor *string `json:"next_cursor,omitempty"`
	PrevCursor *string `json:"prev_cursor,omitempty"`
}

// NewCursorPagePayout instantiates a new CursorPagePayout object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCursorPagePayout() *CursorPagePayout {
	this := CursorPagePayout{}
	return &this
}

// NewCursorPagePayoutWithDefaults instantiates a new CursorPagePayout object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCursorPagePayoutWithDefaults() *CursorPagePayout {
	this := CursorPagePayout{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *CursorPagePayout) GetItems() []Payout {
	if o == nil || o.Items == nil {
		var ret []Payout
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CursorPagePayout) GetItemsOk() (*[]Payout, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CursorPagePayout) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Payout and assigns it to the Items field.
func (o *CursorPagePayout) SetItems(v []Payout) {
	o.Items = &v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *CursorPagePayout) GetNextCursor() string {
	if o == nil || o.NextCursor == nil {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CursorPagePayout) GetNextCursorOk() (*string, bool) {
	if o == nil || o.NextCursor == nil {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *CursorPagePayout) HasNextCursor() bool {
	if o != nil && o.NextCursor != nil {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *CursorPagePayout) SetNextCursor(v string) {
	o.NextCursor = &v
}

// GetPrevCursor returns the PrevCursor field value if set, zero value otherwise.
func (o *CursorPagePayout) GetPrevCursor() string {
	if o == nil || o.PrevCursor == nil {
		var ret string
		return ret
	}
	return *o.PrevCursor
}

// GetPrevCursorOk returns a tuple with the PrevCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CursorPagePayout) GetPrevCursorOk() (*string, bool) {
	if o == nil || o.PrevCursor == nil {
		return nil, false
	}
	return o.PrevCursor, true
}

// HasPrevCursor returns a boolean if a field has been set.
func (o *CursorPagePayout) HasPrevCursor() bool {
	if o != nil && o.PrevCursor != nil {
		return true
	}

	return false
}

// SetPrevCursor gets a reference to the given string and assigns it to the PrevCursor field.
func (o *CursorPagePayout) SetPrevCursor(v string) {
	o.PrevCursor = &v
}

func (o CursorPagePayout) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.NextCursor != nil {
		toSerialize["next_cursor"] = o.NextCursor
	}
	if o.PrevCursor != nil {
		toSerialize["prev_cursor"] = o.PrevCursor
	}
	return json.Marshal(toSerialize)
}

type NullableCursorPagePayout struct {
	value *CursorPagePayout
	isSet bool
}

func (v NullableCursorPagePayout) Get() *CursorPagePayout {
	return v.value
}

func (v *NullableCursorPagePayout) Set(val *CursorPagePayout) {
	v.value = val
	v.isSet = true
}

func (v NullableCursorPagePayout) IsSet() bool {
	return v.isSet
}

func (v *NullableCursorPagePayout) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCursorPagePayout(val *CursorPagePayout) *NullableCursorPagePayout {
	return &NullableCursorPagePayout{value: val, isSet: true}
}

func (v NullableCursorPagePayout) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCursorPagePayout) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


