/*
 * Pay OpenAPI Documentations
 * This is a pay service api server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@openweb3.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.pay.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CryptoCurrencyNetwork
 */
public class CryptoCurrencyNetworkTest {
    private final CryptoCurrencyNetwork model = new CryptoCurrencyNetwork();

    /**
     * Model tests for CryptoCurrencyNetwork
     */
    @Test
    public void testCryptoCurrencyNetwork() {
        // TODO: test CryptoCurrencyNetwork
    }

    /**
     * Test the property 'canDeposit'
     */
    @Test
    public void canDepositTest() {
        // TODO: test canDeposit
    }

    /**
     * Test the property 'canTransfer'
     */
    @Test
    public void canTransferTest() {
        // TODO: test canTransfer
    }

    /**
     * Test the property 'canWithdraw'
     */
    @Test
    public void canWithdrawTest() {
        // TODO: test canWithdraw
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'network'
     */
    @Test
    public void networkTest() {
        // TODO: test network
    }

}
