/*
 * Pay OpenAPI Documentations
 * This is a pay service api server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@openweb3.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.pay.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openweb3.pay.models.Webhook;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CursorPageWebhook
 */
public class CursorPageWebhookTest {
    private final CursorPageWebhook model = new CursorPageWebhook();

    /**
     * Model tests for CursorPageWebhook
     */
    @Test
    public void testCursorPageWebhook() {
        // TODO: test CursorPageWebhook
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'nextCursor'
     */
    @Test
    public void nextCursorTest() {
        // TODO: test nextCursor
    }

    /**
     * Test the property 'prevCursor'
     */
    @Test
    public void prevCursorTest() {
        // TODO: test prevCursor
    }

}
