/*
 * Pay API Documentations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.pay.internal.api;

import io.openweb3.pay.internal.ApiException;
import io.openweb3.pay.models.HTTPValidationError;
import io.openweb3.pay.models.HttpErrorOut;
import io.openweb3.pay.models.InvoiceIn;
import io.openweb3.pay.models.InvoiceOut;
import io.openweb3.pay.models.ListResponseInvoiceOut;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InvoiceApi
 */
@Ignore
public class InvoiceApiTest {

    private final InvoiceApi api = new InvoiceApi();

    
    /**
     * Create invoice
     *
     * Create a new invoice.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1InvoiceCreateTest() throws ApiException {
        String appId = null;
        InvoiceIn invoiceIn = null;
        InvoiceOut response = api.v1InvoiceCreate(appId, invoiceIn);

        // TODO: test validations
    }
    
    /**
     * Get invoice
     *
     * retrieve a specified webhook endpoint.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1InvoiceGetTest() throws ApiException {
        String appId = null;
        String idOrUid = null;
        InvoiceOut response = api.v1InvoiceGet(appId, idOrUid);

        // TODO: test validations
    }
    
    /**
     * List invoices
     *
     * List invoices.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1InvoiceListTest() throws ApiException {
        String appId = null;
        Integer limit = null;
        Integer offset = null;
        String userId = null;
        String channel = null;
        ListResponseInvoiceOut response = api.v1InvoiceList(appId, limit, offset, userId, channel);

        // TODO: test validations
    }
    
}
