/*
 * Pay OpenAPI Documentations
 * This is a pay service api server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@openweb3.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.pay.internal.api;

import io.openweb3.pay.internal.ApiException;
import io.openweb3.pay.models.CreateRefund;
import io.openweb3.pay.models.CursorPageRefund;
import io.openweb3.pay.models.Refund;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RefundApi
 */
@Ignore
public class RefundApiTest {

    private final RefundApi api = new RefundApi();

    
    /**
     * Refund invoice payment
     *
     * Refund invoice payment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1RefundsCreateTest() throws ApiException {
        String appId = null;
        CreateRefund createRefund = null;
        Refund response = api.v1RefundsCreate(appId, createRefund);

        // TODO: test validations
    }
    
    /**
     * List refunds
     *
     * List refunds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1RefundsListTest() throws ApiException {
        String appId = null;
        String cursor = null;
        Integer limit = null;
        Object body = null;
        CursorPageRefund response = api.v1RefundsList(appId, cursor, limit);

        // TODO: test validations
    }
    
    /**
     * Retrieve a refund
     *
     * Retrieve a refund
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1RefundsRetrieveTest() throws ApiException {
        String appId = null;
        String refundId = null;
        Object body = null;
        Refund response = api.v1RefundsRetrieve(appId, refundId);

        // TODO: test validations
    }
    
}
