/*
 * Pay OpenAPI Documentations
 * This is a pay service api server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@openweb3.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.pay.internal.api;

import io.openweb3.pay.internal.ApiException;
import io.openweb3.pay.models.CreateWebhook;
import io.openweb3.pay.models.CursorPageWebhook;
import io.openweb3.pay.models.UpdateWebhook;
import io.openweb3.pay.models.Webhook;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebhookApi
 */
@Ignore
public class WebhookApiTest {

    private final WebhookApi api = new WebhookApi();

    
    /**
     * Create a webhook endpoint
     *
     * Create a webhook endpoint
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1EndpointsCreateTest() throws ApiException {
        String appId = null;
        CreateWebhook createWebhook = null;
        Webhook response = api.v1EndpointsCreate(appId, createWebhook);

        // TODO: test validations
    }
    
    /**
     * Delete a webhook endpoint
     *
     * Delete a webhook endpoint
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1EndpointsDeleteTest() throws ApiException {
        String appId = null;
        String endpointId = null;
        Object body = null;
        Webhook response = api.v1EndpointsDelete(appId, endpointId);

        // TODO: test validations
    }
    
    /**
     * List webhook endpoints
     *
     * List webhook endpoints
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1EndpointsListTest() throws ApiException {
        String appId = null;
        Integer limit = null;
        String cursor = null;
        String ordering = null;
        Object body = null;
        CursorPageWebhook response = api.v1EndpointsList(appId, limit, cursor);

        // TODO: test validations
    }
    
    /**
     * Retrieve a webhook endpoint
     *
     * Retrieve a webhook endpoint
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1EndpointsRetrieveTest() throws ApiException {
        String appId = null;
        String endpointId = null;
        Object body = null;
        Webhook response = api.v1EndpointsRetrieve(appId, endpointId);

        // TODO: test validations
    }
    
    /**
     * Update a webhook endpoint
     *
     * Update a webhook endpoint
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1EndpointsUpdateTest() throws ApiException {
        String appId = null;
        String endpointId = null;
        UpdateWebhook updateWebhook = null;
        Webhook response = api.v1EndpointsUpdate(appId, endpointId, updateWebhook);

        // TODO: test validations
    }
    
}
