/*
 * Pay OpenAPI Documentations
 * This is a pay service api server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@openweb3.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.pay.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreatePayout
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-07T05:09:50.814598+08:00[Asia/Shanghai]")
public class CreatePayout {
  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private String amount;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;

  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  private String network;

  public static final String SERIALIZED_NAME_NOTE = "note";
  @SerializedName(SERIALIZED_NAME_NOTE)
  private String note;

  public static final String SERIALIZED_NAME_TO_ADDRESS = "toAddress";
  @SerializedName(SERIALIZED_NAME_TO_ADDRESS)
  private String toAddress;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;


  public CreatePayout amount(String amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Amount (Integer)
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Amount (Integer)")

  public String getAmount() {
    return amount;
  }


  public void setAmount(String amount) {
    this.amount = amount;
  }


  public CreatePayout currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * Currency Code
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Currency Code")

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public CreatePayout network(String network) {
    
    this.network = network;
    return this;
  }

   /**
   * Currency Network
   * @return network
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Currency Network")

  public String getNetwork() {
    return network;
  }


  public void setNetwork(String network) {
    this.network = network;
  }


  public CreatePayout note(String note) {
    
    this.note = note;
    return this;
  }

   /**
   * Payout notes
   * @return note
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Payout notes")

  public String getNote() {
    return note;
  }


  public void setNote(String note) {
    this.note = note;
  }


  public CreatePayout toAddress(String toAddress) {
    
    this.toAddress = toAddress;
    return this;
  }

   /**
   * To Address
   * @return toAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "To Address")

  public String getToAddress() {
    return toAddress;
  }


  public void setToAddress(String toAddress) {
    this.toAddress = toAddress;
  }


  public CreatePayout userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * User ID
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "User ID")

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePayout createPayout = (CreatePayout) o;
    return Objects.equals(this.amount, createPayout.amount) &&
        Objects.equals(this.currency, createPayout.currency) &&
        Objects.equals(this.network, createPayout.network) &&
        Objects.equals(this.note, createPayout.note) &&
        Objects.equals(this.toAddress, createPayout.toAddress) &&
        Objects.equals(this.userId, createPayout.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, currency, network, note, toAddress, userId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePayout {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    toAddress: ").append(toIndentedString(toAddress)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

