/*
 * Pay OpenAPI Documentations
 * This is a pay service api server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@openweb3.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.pay.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CryptoCurrencyNetwork
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-13T23:46:23.401937+08:00[Asia/Shanghai]")
public class CryptoCurrencyNetwork {
  public static final String SERIALIZED_NAME_CAN_DEPOSIT = "canDeposit";
  @SerializedName(SERIALIZED_NAME_CAN_DEPOSIT)
  private Boolean canDeposit;

  public static final String SERIALIZED_NAME_CAN_TRANSFER = "canTransfer";
  @SerializedName(SERIALIZED_NAME_CAN_TRANSFER)
  private Boolean canTransfer;

  public static final String SERIALIZED_NAME_CAN_WITHDRAW = "canWithdraw";
  @SerializedName(SERIALIZED_NAME_CAN_WITHDRAW)
  private Boolean canWithdraw;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  private String network;


  public CryptoCurrencyNetwork canDeposit(Boolean canDeposit) {
    
    this.canDeposit = canDeposit;
    return this;
  }

   /**
   * Can Deposit
   * @return canDeposit
  **/
  @ApiModelProperty(required = true, value = "Can Deposit")

  public Boolean getCanDeposit() {
    return canDeposit;
  }


  public void setCanDeposit(Boolean canDeposit) {
    this.canDeposit = canDeposit;
  }


  public CryptoCurrencyNetwork canTransfer(Boolean canTransfer) {
    
    this.canTransfer = canTransfer;
    return this;
  }

   /**
   * Can Transfer
   * @return canTransfer
  **/
  @ApiModelProperty(required = true, value = "Can Transfer")

  public Boolean getCanTransfer() {
    return canTransfer;
  }


  public void setCanTransfer(Boolean canTransfer) {
    this.canTransfer = canTransfer;
  }


  public CryptoCurrencyNetwork canWithdraw(Boolean canWithdraw) {
    
    this.canWithdraw = canWithdraw;
    return this;
  }

   /**
   * Can Withdraw
   * @return canWithdraw
  **/
  @ApiModelProperty(required = true, value = "Can Withdraw")

  public Boolean getCanWithdraw() {
    return canWithdraw;
  }


  public void setCanWithdraw(Boolean canWithdraw) {
    this.canWithdraw = canWithdraw;
  }


  public CryptoCurrencyNetwork code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Network code
   * @return code
  **/
  @ApiModelProperty(required = true, value = "Network code")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public CryptoCurrencyNetwork name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Network display name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Network display name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public CryptoCurrencyNetwork network(String network) {
    
    this.network = network;
    return this;
  }

   /**
   * Network name
   * @return network
  **/
  @ApiModelProperty(required = true, value = "Network name")

  public String getNetwork() {
    return network;
  }


  public void setNetwork(String network) {
    this.network = network;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CryptoCurrencyNetwork cryptoCurrencyNetwork = (CryptoCurrencyNetwork) o;
    return Objects.equals(this.canDeposit, cryptoCurrencyNetwork.canDeposit) &&
        Objects.equals(this.canTransfer, cryptoCurrencyNetwork.canTransfer) &&
        Objects.equals(this.canWithdraw, cryptoCurrencyNetwork.canWithdraw) &&
        Objects.equals(this.code, cryptoCurrencyNetwork.code) &&
        Objects.equals(this.name, cryptoCurrencyNetwork.name) &&
        Objects.equals(this.network, cryptoCurrencyNetwork.network);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canDeposit, canTransfer, canWithdraw, code, name, network);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CryptoCurrencyNetwork {\n");
    sb.append("    canDeposit: ").append(toIndentedString(canDeposit)).append("\n");
    sb.append("    canTransfer: ").append(toIndentedString(canTransfer)).append("\n");
    sb.append("    canWithdraw: ").append(toIndentedString(canWithdraw)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

