/*
 * Pay OpenAPI Documentations
 * This is a pay service api server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@openweb3.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.pay.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openweb3.pay.models.CryptoCurrencyNetwork;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CryptoCurrency
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-17T02:08:34.702118+08:00[Asia/Shanghai]")
public class CryptoCurrency {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_DECIMALS = "decimals";
  @SerializedName(SERIALIZED_NAME_DECIMALS)
  private Integer decimals;

  public static final String SERIALIZED_NAME_MAX_WITHDRAW_AMOUNT = "maxWithdrawAmount";
  @SerializedName(SERIALIZED_NAME_MAX_WITHDRAW_AMOUNT)
  private String maxWithdrawAmount;

  public static final String SERIALIZED_NAME_MIN_DEPOSIT_AMOUNT = "minDepositAmount";
  @SerializedName(SERIALIZED_NAME_MIN_DEPOSIT_AMOUNT)
  private String minDepositAmount;

  public static final String SERIALIZED_NAME_MIN_WITHDRAW_AMOUNT = "minWithdrawAmount";
  @SerializedName(SERIALIZED_NAME_MIN_WITHDRAW_AMOUNT)
  private String minWithdrawAmount;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NETWORKS = "networks";
  @SerializedName(SERIALIZED_NAME_NETWORKS)
  private List<CryptoCurrencyNetwork> networks = new ArrayList<>();

  public static final String SERIALIZED_NAME_PRECISION = "precision";
  @SerializedName(SERIALIZED_NAME_PRECISION)
  private Integer precision;


  public CryptoCurrency code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Currency code
   * @return code
  **/
  @ApiModelProperty(required = true, value = "Currency code")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public CryptoCurrency decimals(Integer decimals) {
    
    this.decimals = decimals;
    return this;
  }

   /**
   * Decimals
   * @return decimals
  **/
  @ApiModelProperty(required = true, value = "Decimals")

  public Integer getDecimals() {
    return decimals;
  }


  public void setDecimals(Integer decimals) {
    this.decimals = decimals;
  }


  public CryptoCurrency maxWithdrawAmount(String maxWithdrawAmount) {
    
    this.maxWithdrawAmount = maxWithdrawAmount;
    return this;
  }

   /**
   * Max Withdraw Amount (Integer)
   * @return maxWithdrawAmount
  **/
  @ApiModelProperty(required = true, value = "Max Withdraw Amount (Integer)")

  public String getMaxWithdrawAmount() {
    return maxWithdrawAmount;
  }


  public void setMaxWithdrawAmount(String maxWithdrawAmount) {
    this.maxWithdrawAmount = maxWithdrawAmount;
  }


  public CryptoCurrency minDepositAmount(String minDepositAmount) {
    
    this.minDepositAmount = minDepositAmount;
    return this;
  }

   /**
   * Min Deposit Amount (Integer)
   * @return minDepositAmount
  **/
  @ApiModelProperty(required = true, value = "Min Deposit Amount (Integer)")

  public String getMinDepositAmount() {
    return minDepositAmount;
  }


  public void setMinDepositAmount(String minDepositAmount) {
    this.minDepositAmount = minDepositAmount;
  }


  public CryptoCurrency minWithdrawAmount(String minWithdrawAmount) {
    
    this.minWithdrawAmount = minWithdrawAmount;
    return this;
  }

   /**
   * Min Withdraw Amount (Integer)
   * @return minWithdrawAmount
  **/
  @ApiModelProperty(required = true, value = "Min Withdraw Amount (Integer)")

  public String getMinWithdrawAmount() {
    return minWithdrawAmount;
  }


  public void setMinWithdrawAmount(String minWithdrawAmount) {
    this.minWithdrawAmount = minWithdrawAmount;
  }


  public CryptoCurrency name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Currency name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Currency name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public CryptoCurrency networks(List<CryptoCurrencyNetwork> networks) {
    
    this.networks = networks;
    return this;
  }

  public CryptoCurrency addNetworksItem(CryptoCurrencyNetwork networksItem) {
    this.networks.add(networksItem);
    return this;
  }

   /**
   * Networks
   * @return networks
  **/
  @ApiModelProperty(required = true, value = "Networks")

  public List<CryptoCurrencyNetwork> getNetworks() {
    return networks;
  }


  public void setNetworks(List<CryptoCurrencyNetwork> networks) {
    this.networks = networks;
  }


  public CryptoCurrency precision(Integer precision) {
    
    this.precision = precision;
    return this;
  }

   /**
   * Precision
   * @return precision
  **/
  @ApiModelProperty(required = true, value = "Precision")

  public Integer getPrecision() {
    return precision;
  }


  public void setPrecision(Integer precision) {
    this.precision = precision;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CryptoCurrency cryptoCurrency = (CryptoCurrency) o;
    return Objects.equals(this.code, cryptoCurrency.code) &&
        Objects.equals(this.decimals, cryptoCurrency.decimals) &&
        Objects.equals(this.maxWithdrawAmount, cryptoCurrency.maxWithdrawAmount) &&
        Objects.equals(this.minDepositAmount, cryptoCurrency.minDepositAmount) &&
        Objects.equals(this.minWithdrawAmount, cryptoCurrency.minWithdrawAmount) &&
        Objects.equals(this.name, cryptoCurrency.name) &&
        Objects.equals(this.networks, cryptoCurrency.networks) &&
        Objects.equals(this.precision, cryptoCurrency.precision);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, decimals, maxWithdrawAmount, minDepositAmount, minWithdrawAmount, name, networks, precision);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CryptoCurrency {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    decimals: ").append(toIndentedString(decimals)).append("\n");
    sb.append("    maxWithdrawAmount: ").append(toIndentedString(maxWithdrawAmount)).append("\n");
    sb.append("    minDepositAmount: ").append(toIndentedString(minDepositAmount)).append("\n");
    sb.append("    minWithdrawAmount: ").append(toIndentedString(minWithdrawAmount)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    networks: ").append(toIndentedString(networks)).append("\n");
    sb.append("    precision: ").append(toIndentedString(precision)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

