/*
 * Pay OpenAPI Documentations
 * This is a pay service api server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@openweb3.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.pay.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Payout
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-13T23:46:23.401937+08:00[Asia/Shanghai]")
public class Payout {
  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private String amount;

  public static final String SERIALIZED_NAME_COMPLETED_AT = "completedAt";
  @SerializedName(SERIALIZED_NAME_COMPLETED_AT)
  private String completedAt;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;

  public static final String SERIALIZED_NAME_FAILED_AT = "failedAt";
  @SerializedName(SERIALIZED_NAME_FAILED_AT)
  private String failedAt;

  public static final String SERIALIZED_NAME_FAILED_REASON = "failedReason";
  @SerializedName(SERIALIZED_NAME_FAILED_REASON)
  private String failedReason;

  public static final String SERIALIZED_NAME_FROM_ADDRESS = "fromAddress";
  @SerializedName(SERIALIZED_NAME_FROM_ADDRESS)
  private String fromAddress;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  private String network;

  public static final String SERIALIZED_NAME_NOTE = "note";
  @SerializedName(SERIALIZED_NAME_NOTE)
  private String note;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_TO_ADDRESS = "toAddress";
  @SerializedName(SERIALIZED_NAME_TO_ADDRESS)
  private String toAddress;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;


  public Payout amount(String amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Amount (Integer)
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Amount (Integer)")

  public String getAmount() {
    return amount;
  }


  public void setAmount(String amount) {
    this.amount = amount;
  }


  public Payout completedAt(String completedAt) {
    
    this.completedAt = completedAt;
    return this;
  }

   /**
   * Completed at
   * @return completedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Completed at")

  public String getCompletedAt() {
    return completedAt;
  }


  public void setCompletedAt(String completedAt) {
    this.completedAt = completedAt;
  }


  public Payout createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Created at
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Created at")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public Payout currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * Currency Code
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Currency Code")

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public Payout failedAt(String failedAt) {
    
    this.failedAt = failedAt;
    return this;
  }

   /**
   * Failed at
   * @return failedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Failed at")

  public String getFailedAt() {
    return failedAt;
  }


  public void setFailedAt(String failedAt) {
    this.failedAt = failedAt;
  }


  public Payout failedReason(String failedReason) {
    
    this.failedReason = failedReason;
    return this;
  }

   /**
   * Failed reason
   * @return failedReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Failed reason")

  public String getFailedReason() {
    return failedReason;
  }


  public void setFailedReason(String failedReason) {
    this.failedReason = failedReason;
  }


  public Payout fromAddress(String fromAddress) {
    
    this.fromAddress = fromAddress;
    return this;
  }

   /**
   * From Address
   * @return fromAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "From Address")

  public String getFromAddress() {
    return fromAddress;
  }


  public void setFromAddress(String fromAddress) {
    this.fromAddress = fromAddress;
  }


  public Payout id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Payout network(String network) {
    
    this.network = network;
    return this;
  }

   /**
   * Currency Network
   * @return network
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Currency Network")

  public String getNetwork() {
    return network;
  }


  public void setNetwork(String network) {
    this.network = network;
  }


  public Payout note(String note) {
    
    this.note = note;
    return this;
  }

   /**
   * Payout note
   * @return note
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Payout note")

  public String getNote() {
    return note;
  }


  public void setNote(String note) {
    this.note = note;
  }


  public Payout status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Payout status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Payout status")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public Payout toAddress(String toAddress) {
    
    this.toAddress = toAddress;
    return this;
  }

   /**
   * To Address
   * @return toAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "To Address")

  public String getToAddress() {
    return toAddress;
  }


  public void setToAddress(String toAddress) {
    this.toAddress = toAddress;
  }


  public Payout updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Updated at
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Updated at")

  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public Payout userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * User ID
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "User ID")

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Payout payout = (Payout) o;
    return Objects.equals(this.amount, payout.amount) &&
        Objects.equals(this.completedAt, payout.completedAt) &&
        Objects.equals(this.createdAt, payout.createdAt) &&
        Objects.equals(this.currency, payout.currency) &&
        Objects.equals(this.failedAt, payout.failedAt) &&
        Objects.equals(this.failedReason, payout.failedReason) &&
        Objects.equals(this.fromAddress, payout.fromAddress) &&
        Objects.equals(this.id, payout.id) &&
        Objects.equals(this.network, payout.network) &&
        Objects.equals(this.note, payout.note) &&
        Objects.equals(this.status, payout.status) &&
        Objects.equals(this.toAddress, payout.toAddress) &&
        Objects.equals(this.updatedAt, payout.updatedAt) &&
        Objects.equals(this.userId, payout.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, completedAt, createdAt, currency, failedAt, failedReason, fromAddress, id, network, note, status, toAddress, updatedAt, userId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Payout {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    completedAt: ").append(toIndentedString(completedAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    failedAt: ").append(toIndentedString(failedAt)).append("\n");
    sb.append("    failedReason: ").append(toIndentedString(failedReason)).append("\n");
    sb.append("    fromAddress: ").append(toIndentedString(fromAddress)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    toAddress: ").append(toIndentedString(toAddress)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

