/*
 * Pay OpenAPI Documentations
 * This is a pay service api server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@openweb3.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.pay.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Refund
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-17T02:08:34.702118+08:00[Asia/Shanghai]")
public class Refund {
  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private String amount;

  public static final String SERIALIZED_NAME_COMPLETED_AT = "completed_at";
  @SerializedName(SERIALIZED_NAME_COMPLETED_AT)
  private String completedAt;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_FAILED_AT = "failed_at";
  @SerializedName(SERIALIZED_NAME_FAILED_AT)
  private String failedAt;

  public static final String SERIALIZED_NAME_FAILED_REASON = "failed_reason";
  @SerializedName(SERIALIZED_NAME_FAILED_REASON)
  private String failedReason;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NOTE = "note";
  @SerializedName(SERIALIZED_NAME_NOTE)
  private String note;

  public static final String SERIALIZED_NAME_PAYMENT_ID = "payment_id";
  @SerializedName(SERIALIZED_NAME_PAYMENT_ID)
  private String paymentId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_TO_ADDRESS = "to_address";
  @SerializedName(SERIALIZED_NAME_TO_ADDRESS)
  private String toAddress;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;


  public Refund amount(String amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Refund amount (Integer)
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Refund amount (Integer)")

  public String getAmount() {
    return amount;
  }


  public void setAmount(String amount) {
    this.amount = amount;
  }


  public Refund completedAt(String completedAt) {
    
    this.completedAt = completedAt;
    return this;
  }

   /**
   * Completed at
   * @return completedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Completed at")

  public String getCompletedAt() {
    return completedAt;
  }


  public void setCompletedAt(String completedAt) {
    this.completedAt = completedAt;
  }


  public Refund createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Created at
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Created at")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public Refund failedAt(String failedAt) {
    
    this.failedAt = failedAt;
    return this;
  }

   /**
   * Failed at
   * @return failedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Failed at")

  public String getFailedAt() {
    return failedAt;
  }


  public void setFailedAt(String failedAt) {
    this.failedAt = failedAt;
  }


  public Refund failedReason(String failedReason) {
    
    this.failedReason = failedReason;
    return this;
  }

   /**
   * Failed reason
   * @return failedReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Failed reason")

  public String getFailedReason() {
    return failedReason;
  }


  public void setFailedReason(String failedReason) {
    this.failedReason = failedReason;
  }


  public Refund id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Refund note(String note) {
    
    this.note = note;
    return this;
  }

   /**
   * Refund note
   * @return note
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Refund note")

  public String getNote() {
    return note;
  }


  public void setNote(String note) {
    this.note = note;
  }


  public Refund paymentId(String paymentId) {
    
    this.paymentId = paymentId;
    return this;
  }

   /**
   * Payment ID
   * @return paymentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Payment ID")

  public String getPaymentId() {
    return paymentId;
  }


  public void setPaymentId(String paymentId) {
    this.paymentId = paymentId;
  }


  public Refund status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Refund status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Refund status")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public Refund toAddress(String toAddress) {
    
    this.toAddress = toAddress;
    return this;
  }

   /**
   * To Address
   * @return toAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "To Address")

  public String getToAddress() {
    return toAddress;
  }


  public void setToAddress(String toAddress) {
    this.toAddress = toAddress;
  }


  public Refund updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Updated at
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Updated at")

  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Refund refund = (Refund) o;
    return Objects.equals(this.amount, refund.amount) &&
        Objects.equals(this.completedAt, refund.completedAt) &&
        Objects.equals(this.createdAt, refund.createdAt) &&
        Objects.equals(this.failedAt, refund.failedAt) &&
        Objects.equals(this.failedReason, refund.failedReason) &&
        Objects.equals(this.id, refund.id) &&
        Objects.equals(this.note, refund.note) &&
        Objects.equals(this.paymentId, refund.paymentId) &&
        Objects.equals(this.status, refund.status) &&
        Objects.equals(this.toAddress, refund.toAddress) &&
        Objects.equals(this.updatedAt, refund.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, completedAt, createdAt, failedAt, failedReason, id, note, paymentId, status, toAddress, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Refund {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    completedAt: ").append(toIndentedString(completedAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    failedAt: ").append(toIndentedString(failedAt)).append("\n");
    sb.append("    failedReason: ").append(toIndentedString(failedReason)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    paymentId: ").append(toIndentedString(paymentId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    toAddress: ").append(toIndentedString(toAddress)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

