/**
 * Pay OpenAPI Documentations
 * This is a pay service api server.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@openweb3.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateRefund {
    /**
    * Refund amount (Integer)
    */
    'amount'?: string;
    /**
    * Refund note
    */
    'note'?: string;
    /**
    * Payment ID
    */
    'paymentId'?: string;
    /**
    * To Address
    */
    'toAddress'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentId",
            "baseName": "payment_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAddress",
            "baseName": "to_address",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateRefund.attributeTypeMap;
    }
    
    public constructor() {
    }
}

