/**
 * Pay OpenAPI Documentations
 * This is a pay service api server.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@openweb3.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreatePaymentRequest {
    /**
    * Amount (Integer)
    */
    'amount': string;
    /**
    * Currency
    */
    'currency': string;
    /**
    * Expiration
    */
    'expiration'?: number;
    /**
    * Extra
    */
    'extra'?: { [key: string]: any; };
    /**
    * Metadata
    */
    'metadata'?: { [key: string]: any; };
    /**
    * Note
    */
    'note'?: string;
    /**
    * PaymentMethod
    */
    'paymentMethod': string;
    /**
    * PaymentProvider
    */
    'paymentProvider': string;
    /**
    * Unique ID
    */
    'uid'?: string;
    /**
    * User ID
    */
    'userId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiration",
            "baseName": "expiration",
            "type": "number",
            "format": ""
        },
        {
            "name": "extra",
            "baseName": "extra",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentMethod",
            "baseName": "payment_method",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentProvider",
            "baseName": "payment_provider",
            "type": "string",
            "format": ""
        },
        {
            "name": "uid",
            "baseName": "uid",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreatePaymentRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

