/**
 * Pay OpenAPI Documentations
 * This is a pay service api server.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@openweb3.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class FiatCurrency {
  static readonly discriminator: string | undefined = undefined;
  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      "name": "code",
      "baseName": "code",
      "type": "string",
      "format": "",
    },
    {
      "name": "name",
      "baseName": "name",
      "type": "string",
      "format": "",
    }];
  /**
   * Currency Code
   */
  "code"?: string;
  /**
   * Currency Name
   */
  "name"?: string;

  static getAttributeTypeMap() {
    return FiatCurrency.attributeTypeMap;
  }
}

