/**
 * Wallet Pay API Documentations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class OrderOut {
    /**
    * The order's ID
    */
    'id': string;
    'metadata': { [key: string]: string; };
    /**
    * The order's creator
    */
    'userId'?: string;
    /**
    * The order's UID
    */
    'uid'?: string;
    /**
    * Order channel
    */
    'channel': string;
    /**
    * Blockchain code
    */
    'chain': string;
    /**
    * Currency code
    */
    'currency': string;
    /**
    * Big decimal string representation. Note that the max precision (number of digits after decimal point) depends on the currencyCode. E.g. for all fiat currencies is 2 (0.01), for BTC is 8, for USDT is 6. There's also min order amount for creating an order. It's 0.000001 BTC / 0.01 USDT / 0.01 USD / 0.01 EUR / 0.1 RUB.
    */
    'amount': string;
    /**
    * The payment token from payment channel
    */
    'credentials'?: string;
    /**
    * The order's creation time
    */
    'createdAt': Date;
    /**
    * The order's paid time
    */
    'paidAt'?: Date;
    /**
    * The order's status 0 - processing 1 - paid 2 - failed 3 - canceled
    */
    'status': number;
    /**
    * The message when order failed
    */
    'failedMessage'?: string;
    /**
    * The order's cancel time
    */
    'canceledAt'?: Date;
    /**
    * The order's failure time
    */
    'failedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": ""
        },
        {
            "name": "uid",
            "baseName": "uid",
            "type": "string",
            "format": ""
        },
        {
            "name": "channel",
            "baseName": "channel",
            "type": "string",
            "format": ""
        },
        {
            "name": "chain",
            "baseName": "chain",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "credentials",
            "baseName": "credentials",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "paidAt",
            "baseName": "paidAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": ""
        },
        {
            "name": "failedMessage",
            "baseName": "failedMessage",
            "type": "string",
            "format": ""
        },
        {
            "name": "canceledAt",
            "baseName": "canceledAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "failedAt",
            "baseName": "failedAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return OrderOut.attributeTypeMap;
    }
    
    public constructor() {
    }
}

