/**
 * Pay OpenAPI Documentations
 * This is a pay service api server.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@openweb3.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class Rate {
  static readonly discriminator: string | undefined = undefined;
  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      "name": "fromCurrency",
      "baseName": "fromCurrency",
      "type": "string",
      "format": "",
    },
    {
      "name": "rate",
      "baseName": "rate",
      "type": "string",
      "format": "",
    },
    {
      "name": "toCurrency",
      "baseName": "toCurrency",
      "type": "string",
      "format": "",
    }];
  /**
   * From currency code
   */
  "fromCurrency"?: string;
  /**
   * Exchange Rate
   */
  "rate"?: string;
  /**
   * To currency code
   */
  "toCurrency"?: string;

  static getAttributeTypeMap() {
    return Rate.attributeTypeMap;
  }
}

