/**
 * Pay OpenAPI Documentations
 * This is a pay service api server.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@openweb3.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Refund {
    /**
    * Refund amount (Integer)
    */
    'amount'?: number;
    /**
    * Completed at
    */
    'completedAt'?: string;
    /**
    * Created at
    */
    'createdAt'?: string;
    /**
    * Failed at
    */
    'failedAt'?: string;
    /**
    * Failed reason
    */
    'failedReason'?: string;
    'id'?: string;
    /**
    * Invoice ID
    */
    'invoiceId'?: string;
    /**
    * Refund note
    */
    'note'?: string;
    /**
    * Refund status
    */
    'status'?: string;
    /**
    * To Address
    */
    'toAddress'?: string;
    /**
    * Updated at
    */
    'updatedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "completedAt",
            "baseName": "completedAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "failedAt",
            "baseName": "failedAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "failedReason",
            "baseName": "failedReason",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "invoiceId",
            "baseName": "invoiceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAddress",
            "baseName": "toAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Refund.attributeTypeMap;
    }
    
    public constructor() {
    }
}

