/**
 * Pay OpenAPI Documentations
 * This is a pay service api server.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@openweb3.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class Webhook {
  static readonly discriminator: string | undefined = undefined;
  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      "name": "createdAt",
      "baseName": "createdAt",
      "type": "string",
      "format": "",
    },
    {
      "name": "description",
      "baseName": "description",
      "type": "string",
      "format": "",
    },
    {
      "name": "disabled",
      "baseName": "disabled",
      "type": "boolean",
      "format": "",
    },
    {
      "name": "eventTypes",
      "baseName": "eventTypes",
      "type": "Array<string>",
      "format": "",
    },
    {
      "name": "filter",
      "baseName": "filter",
      "type": "string",
      "format": "",
    },
    {
      "name": "headers",
      "baseName": "headers",
      "type": "{ [key: string]: string; }",
      "format": "",
    },
    {
      "name": "id",
      "baseName": "id",
      "type": "string",
      "format": "",
    },
    {
      "name": "metadata",
      "baseName": "metadata",
      "type": "{ [key: string]: any; }",
      "format": "",
    },
    {
      "name": "uid",
      "baseName": "uid",
      "type": "string",
      "format": "",
    },
    {
      "name": "url",
      "baseName": "url",
      "type": "string",
      "format": "",
    }];
  "createdAt"?: string;
  "description"?: string;
  "disabled"?: boolean;
  "eventTypes"?: Array<string>;
  "filter"?: string;
  "headers"?: { [key: string]: string };
  "id"?: string;
  "metadata"?: { [key: string]: any };
  "uid"?: string;
  "url"?: string;

  static getAttributeTypeMap() {
    return Webhook.attributeTypeMap;
  }
}

