/**
 * Wallet Pay API Documentations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class WebhookOut {
    /**
    * The webhook's UID
    */
    'uid'?: string;
    /**
    * The chain network monitor by webhook
    */
    'network': string;
    /**
    * Blockchain code
    */
    'chain': string;
    /**
    * The webhook's description
    */
    'description'?: string;
    /**
    * The webhook endpoint url
    */
    'url': string;
    /**
    * The webhook endpoint url
    */
    'filter'?: string;
    /**
    * The webhook endpoint url
    */
    'filterTypes': Array<string>;
    /**
    * indicate whether to disable the webhook endpoint
    */
    'disabled'?: boolean;
    /**
    * Optional metadata
    */
    'metadata'?: { [key: string]: string; };
    /**
    * Optional metadata
    */
    'headers'?: { [key: string]: string; };
    /**
    * webhook version
    */
    'version'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uid",
            "baseName": "uid",
            "type": "string",
            "format": ""
        },
        {
            "name": "network",
            "baseName": "network",
            "type": "string",
            "format": ""
        },
        {
            "name": "chain",
            "baseName": "chain",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "string",
            "format": ""
        },
        {
            "name": "filterTypes",
            "baseName": "filterTypes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "disabled",
            "baseName": "disabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WebhookOut.attributeTypeMap;
    }
    
    public constructor() {
    }
}

