/*
 * Pay OpenAPI Documentations
 * This is a pay service api server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@openweb3.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.pay.internal.api;

import io.openweb3.pay.internal.ApiCallback;
import io.openweb3.pay.internal.ApiClient;
import io.openweb3.pay.internal.ApiException;
import io.openweb3.pay.internal.ApiResponse;
import io.openweb3.pay.internal.Configuration;
import io.openweb3.pay.internal.Pair;
import io.openweb3.pay.internal.ProgressRequestBody;
import io.openweb3.pay.internal.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.openweb3.pay.models.CreatePaymentRequest;
import io.openweb3.pay.models.PagePayment;
import io.openweb3.pay.models.Payment;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PaymentApi {
    private ApiClient localVarApiClient;

    public PaymentApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PaymentApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for v1PaymentsCreate
     * @param appId App ID (required)
     * @param createPaymentRequest Request body (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1PaymentsCreateCall(String appId, CreatePaymentRequest createPaymentRequest, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = createPaymentRequest;

        // create path and map variables
        String localVarPath = "/api/v1/apps/{app_id}/payments"
            .replaceAll("\\{" + "app_id" + "\\}", localVarApiClient.escapeString(appId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1PaymentsCreateValidateBeforeCall(String appId, CreatePaymentRequest createPaymentRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'appId' is set
        if (appId == null) {
            throw new ApiException("Missing the required parameter 'appId' when calling v1PaymentsCreate(Async)");
        }
        
        // verify the required parameter 'createPaymentRequest' is set
        if (createPaymentRequest == null) {
            throw new ApiException("Missing the required parameter 'createPaymentRequest' when calling v1PaymentsCreate(Async)");
        }
        

        okhttp3.Call localVarCall = v1PaymentsCreateCall(appId, createPaymentRequest, _callback);
        return localVarCall;

    }

    /**
     * Create an Payment
     * Create an Payment
     * @param appId App ID (required)
     * @param createPaymentRequest Request body (required)
     * @return Payment
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Payment v1PaymentsCreate(String appId, CreatePaymentRequest createPaymentRequest) throws ApiException {
        ApiResponse<Payment> localVarResp = v1PaymentsCreateWithHttpInfo(appId, createPaymentRequest);
        return localVarResp.getData();
    }

    /**
     * Create an Payment
     * Create an Payment
     * @param appId App ID (required)
     * @param createPaymentRequest Request body (required)
     * @return ApiResponse&lt;Payment&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Payment> v1PaymentsCreateWithHttpInfo(String appId, CreatePaymentRequest createPaymentRequest) throws ApiException {
        okhttp3.Call localVarCall = v1PaymentsCreateValidateBeforeCall(appId, createPaymentRequest, null);
        Type localVarReturnType = new TypeToken<Payment>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create an Payment (asynchronously)
     * Create an Payment
     * @param appId App ID (required)
     * @param createPaymentRequest Request body (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1PaymentsCreateAsync(String appId, CreatePaymentRequest createPaymentRequest, final ApiCallback<Payment> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1PaymentsCreateValidateBeforeCall(appId, createPaymentRequest, _callback);
        Type localVarReturnType = new TypeToken<Payment>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1PaymentsList
     * @param appId App ID (required)
     * @param paymentMethod  (optional)
     * @param userId  (optional)
     * @param offset  (optional)
     * @param limit  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1PaymentsListCall(String appId, String paymentMethod, String userId, Integer offset, Integer limit, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/apps/{app_id}/payments"
            .replaceAll("\\{" + "app_id" + "\\}", localVarApiClient.escapeString(appId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (paymentMethod != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("payment_method", paymentMethod));
        }

        if (userId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("userId", userId));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1PaymentsListValidateBeforeCall(String appId, String paymentMethod, String userId, Integer offset, Integer limit, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'appId' is set
        if (appId == null) {
            throw new ApiException("Missing the required parameter 'appId' when calling v1PaymentsList(Async)");
        }
        

        okhttp3.Call localVarCall = v1PaymentsListCall(appId, paymentMethod, userId, offset, limit, _callback);
        return localVarCall;

    }

    /**
     * List Payments
     * List Payments
     * @param appId App ID (required)
     * @param paymentMethod  (optional)
     * @param userId  (optional)
     * @param offset  (optional)
     * @param limit  (optional)
     * @return PagePayment
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public PagePayment v1PaymentsList(String appId, String paymentMethod, String userId, Integer offset, Integer limit) throws ApiException {
        ApiResponse<PagePayment> localVarResp = v1PaymentsListWithHttpInfo(appId, paymentMethod, userId, offset, limit);
        return localVarResp.getData();
    }

    /**
     * List Payments
     * List Payments
     * @param appId App ID (required)
     * @param paymentMethod  (optional)
     * @param userId  (optional)
     * @param offset  (optional)
     * @param limit  (optional)
     * @return ApiResponse&lt;PagePayment&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PagePayment> v1PaymentsListWithHttpInfo(String appId, String paymentMethod, String userId, Integer offset, Integer limit) throws ApiException {
        okhttp3.Call localVarCall = v1PaymentsListValidateBeforeCall(appId, paymentMethod, userId, offset, limit, null);
        Type localVarReturnType = new TypeToken<PagePayment>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List Payments (asynchronously)
     * List Payments
     * @param appId App ID (required)
     * @param paymentMethod  (optional)
     * @param userId  (optional)
     * @param offset  (optional)
     * @param limit  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1PaymentsListAsync(String appId, String paymentMethod, String userId, Integer offset, Integer limit, final ApiCallback<PagePayment> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1PaymentsListValidateBeforeCall(appId, paymentMethod, userId, offset, limit, _callback);
        Type localVarReturnType = new TypeToken<PagePayment>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1PaymentsRetrieve
     * @param appId App ID (required)
     * @param paymentId Payment ID / UID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1PaymentsRetrieveCall(String appId, String paymentId, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/apps/{app_id}/payments/{payment_id}"
            .replaceAll("\\{" + "app_id" + "\\}", localVarApiClient.escapeString(appId.toString()))
            .replaceAll("\\{" + "payment_id" + "\\}", localVarApiClient.escapeString(paymentId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1PaymentsRetrieveValidateBeforeCall(String appId, String paymentId, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'appId' is set
        if (appId == null) {
            throw new ApiException("Missing the required parameter 'appId' when calling v1PaymentsRetrieve(Async)");
        }
        
        // verify the required parameter 'paymentId' is set
        if (paymentId == null) {
            throw new ApiException("Missing the required parameter 'paymentId' when calling v1PaymentsRetrieve(Async)");
        }
        

        okhttp3.Call localVarCall = v1PaymentsRetrieveCall(appId, paymentId, _callback);
        return localVarCall;

    }

    /**
     * Retrieve an Payment
     * Retrieve an Payment
     * @param appId App ID (required)
     * @param paymentId Payment ID / UID (required)
     * @return Payment
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Payment v1PaymentsRetrieve(String appId, String paymentId) throws ApiException {
        ApiResponse<Payment> localVarResp = v1PaymentsRetrieveWithHttpInfo(appId, paymentId);
        return localVarResp.getData();
    }

    /**
     * Retrieve an Payment
     * Retrieve an Payment
     * @param appId App ID (required)
     * @param paymentId Payment ID / UID (required)
     * @return ApiResponse&lt;Payment&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Payment> v1PaymentsRetrieveWithHttpInfo(String appId, String paymentId) throws ApiException {
        okhttp3.Call localVarCall = v1PaymentsRetrieveValidateBeforeCall(appId, paymentId, null);
        Type localVarReturnType = new TypeToken<Payment>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve an Payment (asynchronously)
     * Retrieve an Payment
     * @param appId App ID (required)
     * @param paymentId Payment ID / UID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1PaymentsRetrieveAsync(String appId, String paymentId, final ApiCallback<Payment> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1PaymentsRetrieveValidateBeforeCall(appId, paymentId, _callback);
        Type localVarReturnType = new TypeToken<Payment>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
