/*
 * Pay OpenAPI Documentations
 * This is a pay service api server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@openweb3.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.pay.internal.api;

import io.openweb3.pay.internal.ApiCallback;
import io.openweb3.pay.internal.ApiClient;
import io.openweb3.pay.internal.ApiException;
import io.openweb3.pay.internal.ApiResponse;
import io.openweb3.pay.internal.Configuration;
import io.openweb3.pay.internal.Pair;
import io.openweb3.pay.internal.ProgressRequestBody;
import io.openweb3.pay.internal.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.openweb3.pay.models.CreateWebhook;
import io.openweb3.pay.models.CursorPageWebhook;
import io.openweb3.pay.models.UpdateWebhook;
import io.openweb3.pay.models.Webhook;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class WebhookApi {
    private ApiClient localVarApiClient;

    public WebhookApi() {
        this(Configuration.getDefaultApiClient());
    }

    public WebhookApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for v1EndpointsCreate
     * @param appId App ID (required)
     * @param createWebhook Request body (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1EndpointsCreateCall(String appId, CreateWebhook createWebhook, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = createWebhook;

        // create path and map variables
        String localVarPath = "/api/v1/apps/{app_id}/endpoints"
            .replaceAll("\\{" + "app_id" + "\\}", localVarApiClient.escapeString(appId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1EndpointsCreateValidateBeforeCall(String appId, CreateWebhook createWebhook, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'appId' is set
        if (appId == null) {
            throw new ApiException("Missing the required parameter 'appId' when calling v1EndpointsCreate(Async)");
        }
        
        // verify the required parameter 'createWebhook' is set
        if (createWebhook == null) {
            throw new ApiException("Missing the required parameter 'createWebhook' when calling v1EndpointsCreate(Async)");
        }
        

        okhttp3.Call localVarCall = v1EndpointsCreateCall(appId, createWebhook, _callback);
        return localVarCall;

    }

    /**
     * Create a webhook endpoint
     * Create a webhook endpoint
     * @param appId App ID (required)
     * @param createWebhook Request body (required)
     * @return Webhook
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Webhook v1EndpointsCreate(String appId, CreateWebhook createWebhook) throws ApiException {
        ApiResponse<Webhook> localVarResp = v1EndpointsCreateWithHttpInfo(appId, createWebhook);
        return localVarResp.getData();
    }

    /**
     * Create a webhook endpoint
     * Create a webhook endpoint
     * @param appId App ID (required)
     * @param createWebhook Request body (required)
     * @return ApiResponse&lt;Webhook&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Webhook> v1EndpointsCreateWithHttpInfo(String appId, CreateWebhook createWebhook) throws ApiException {
        okhttp3.Call localVarCall = v1EndpointsCreateValidateBeforeCall(appId, createWebhook, null);
        Type localVarReturnType = new TypeToken<Webhook>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a webhook endpoint (asynchronously)
     * Create a webhook endpoint
     * @param appId App ID (required)
     * @param createWebhook Request body (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1EndpointsCreateAsync(String appId, CreateWebhook createWebhook, final ApiCallback<Webhook> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1EndpointsCreateValidateBeforeCall(appId, createWebhook, _callback);
        Type localVarReturnType = new TypeToken<Webhook>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1EndpointsDelete
     * @param appId App ID (required)
     * @param endpointId Endpoint ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1EndpointsDeleteCall(String appId, String endpointId, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/apps/{app_id}/endpoints/{endpoint_id}"
            .replaceAll("\\{" + "app_id" + "\\}", localVarApiClient.escapeString(appId.toString()))
            .replaceAll("\\{" + "endpoint_id" + "\\}", localVarApiClient.escapeString(endpointId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1EndpointsDeleteValidateBeforeCall(String appId, String endpointId, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'appId' is set
        if (appId == null) {
            throw new ApiException("Missing the required parameter 'appId' when calling v1EndpointsDelete(Async)");
        }
        
        // verify the required parameter 'endpointId' is set
        if (endpointId == null) {
            throw new ApiException("Missing the required parameter 'endpointId' when calling v1EndpointsDelete(Async)");
        }
        

        okhttp3.Call localVarCall = v1EndpointsDeleteCall(appId, endpointId, _callback);
        return localVarCall;

    }

    /**
     * Delete a webhook endpoint
     * Delete a webhook endpoint
     * @param appId App ID (required)
     * @param endpointId Endpoint ID (required)
     * @return Webhook
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Webhook v1EndpointsDelete(String appId, String endpointId) throws ApiException {
        ApiResponse<Webhook> localVarResp = v1EndpointsDeleteWithHttpInfo(appId, endpointId);
        return localVarResp.getData();
    }

    /**
     * Delete a webhook endpoint
     * Delete a webhook endpoint
     * @param appId App ID (required)
     * @param endpointId Endpoint ID (required)
     * @return ApiResponse&lt;Webhook&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Webhook> v1EndpointsDeleteWithHttpInfo(String appId, String endpointId) throws ApiException {
        okhttp3.Call localVarCall = v1EndpointsDeleteValidateBeforeCall(appId, endpointId, null);
        Type localVarReturnType = new TypeToken<Webhook>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete a webhook endpoint (asynchronously)
     * Delete a webhook endpoint
     * @param appId App ID (required)
     * @param endpointId Endpoint ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1EndpointsDeleteAsync(String appId, String endpointId, final ApiCallback<Webhook> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1EndpointsDeleteValidateBeforeCall(appId, endpointId, _callback);
        Type localVarReturnType = new TypeToken<Webhook>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1EndpointsList
     * @param appId App ID (required)
     * @param limit  (required)
     * @param cursor  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1EndpointsListCall(String appId, Integer limit, String cursor, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/apps/{app_id}/endpoints"
            .replaceAll("\\{" + "app_id" + "\\}", localVarApiClient.escapeString(appId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (cursor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cursor", cursor));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1EndpointsListValidateBeforeCall(String appId, Integer limit, String cursor, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'appId' is set
        if (appId == null) {
            throw new ApiException("Missing the required parameter 'appId' when calling v1EndpointsList(Async)");
        }
        
        // verify the required parameter 'limit' is set
        if (limit == null) {
            throw new ApiException("Missing the required parameter 'limit' when calling v1EndpointsList(Async)");
        }
        

        okhttp3.Call localVarCall = v1EndpointsListCall(appId, limit, cursor, _callback);
        return localVarCall;

    }

    /**
     * List webhook endpoints
     * List webhook endpoints
     * @param appId App ID (required)
     * @param limit  (required)
     * @param cursor  (optional)
     * @return CursorPageWebhook
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public CursorPageWebhook v1EndpointsList(String appId, Integer limit, String cursor) throws ApiException {
        ApiResponse<CursorPageWebhook> localVarResp = v1EndpointsListWithHttpInfo(appId, limit, cursor);
        return localVarResp.getData();
    }

    /**
     * List webhook endpoints
     * List webhook endpoints
     * @param appId App ID (required)
     * @param limit  (required)
     * @param cursor  (optional)
     * @return ApiResponse&lt;CursorPageWebhook&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CursorPageWebhook> v1EndpointsListWithHttpInfo(String appId, Integer limit, String cursor) throws ApiException {
        okhttp3.Call localVarCall = v1EndpointsListValidateBeforeCall(appId, limit, cursor, null);
        Type localVarReturnType = new TypeToken<CursorPageWebhook>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List webhook endpoints (asynchronously)
     * List webhook endpoints
     * @param appId App ID (required)
     * @param limit  (required)
     * @param cursor  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1EndpointsListAsync(String appId, Integer limit, String cursor, final ApiCallback<CursorPageWebhook> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1EndpointsListValidateBeforeCall(appId, limit, cursor, _callback);
        Type localVarReturnType = new TypeToken<CursorPageWebhook>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1EndpointsRetrieve
     * @param appId App ID (required)
     * @param endpointId Endpoint ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1EndpointsRetrieveCall(String appId, String endpointId, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/apps/{app_id}/endpoints/{endpoint_id}"
            .replaceAll("\\{" + "app_id" + "\\}", localVarApiClient.escapeString(appId.toString()))
            .replaceAll("\\{" + "endpoint_id" + "\\}", localVarApiClient.escapeString(endpointId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1EndpointsRetrieveValidateBeforeCall(String appId, String endpointId, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'appId' is set
        if (appId == null) {
            throw new ApiException("Missing the required parameter 'appId' when calling v1EndpointsRetrieve(Async)");
        }
        
        // verify the required parameter 'endpointId' is set
        if (endpointId == null) {
            throw new ApiException("Missing the required parameter 'endpointId' when calling v1EndpointsRetrieve(Async)");
        }
        

        okhttp3.Call localVarCall = v1EndpointsRetrieveCall(appId, endpointId, _callback);
        return localVarCall;

    }

    /**
     * Retrieve a webhook endpoint
     * Retrieve a webhook endpoint
     * @param appId App ID (required)
     * @param endpointId Endpoint ID (required)
     * @return Webhook
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Webhook v1EndpointsRetrieve(String appId, String endpointId) throws ApiException {
        ApiResponse<Webhook> localVarResp = v1EndpointsRetrieveWithHttpInfo(appId, endpointId);
        return localVarResp.getData();
    }

    /**
     * Retrieve a webhook endpoint
     * Retrieve a webhook endpoint
     * @param appId App ID (required)
     * @param endpointId Endpoint ID (required)
     * @return ApiResponse&lt;Webhook&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Webhook> v1EndpointsRetrieveWithHttpInfo(String appId, String endpointId) throws ApiException {
        okhttp3.Call localVarCall = v1EndpointsRetrieveValidateBeforeCall(appId, endpointId, null);
        Type localVarReturnType = new TypeToken<Webhook>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve a webhook endpoint (asynchronously)
     * Retrieve a webhook endpoint
     * @param appId App ID (required)
     * @param endpointId Endpoint ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1EndpointsRetrieveAsync(String appId, String endpointId, final ApiCallback<Webhook> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1EndpointsRetrieveValidateBeforeCall(appId, endpointId, _callback);
        Type localVarReturnType = new TypeToken<Webhook>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1EndpointsUpdate
     * @param appId App ID (required)
     * @param endpointId Endpoint ID (required)
     * @param updateWebhook Request body (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1EndpointsUpdateCall(String appId, String endpointId, UpdateWebhook updateWebhook, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = updateWebhook;

        // create path and map variables
        String localVarPath = "/api/v1/apps/{app_id}/endpoints/{endpoint_id}"
            .replaceAll("\\{" + "app_id" + "\\}", localVarApiClient.escapeString(appId.toString()))
            .replaceAll("\\{" + "endpoint_id" + "\\}", localVarApiClient.escapeString(endpointId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1EndpointsUpdateValidateBeforeCall(String appId, String endpointId, UpdateWebhook updateWebhook, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'appId' is set
        if (appId == null) {
            throw new ApiException("Missing the required parameter 'appId' when calling v1EndpointsUpdate(Async)");
        }
        
        // verify the required parameter 'endpointId' is set
        if (endpointId == null) {
            throw new ApiException("Missing the required parameter 'endpointId' when calling v1EndpointsUpdate(Async)");
        }
        
        // verify the required parameter 'updateWebhook' is set
        if (updateWebhook == null) {
            throw new ApiException("Missing the required parameter 'updateWebhook' when calling v1EndpointsUpdate(Async)");
        }
        

        okhttp3.Call localVarCall = v1EndpointsUpdateCall(appId, endpointId, updateWebhook, _callback);
        return localVarCall;

    }

    /**
     * Update a webhook endpoint
     * Update a webhook endpoint
     * @param appId App ID (required)
     * @param endpointId Endpoint ID (required)
     * @param updateWebhook Request body (required)
     * @return Webhook
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Webhook v1EndpointsUpdate(String appId, String endpointId, UpdateWebhook updateWebhook) throws ApiException {
        ApiResponse<Webhook> localVarResp = v1EndpointsUpdateWithHttpInfo(appId, endpointId, updateWebhook);
        return localVarResp.getData();
    }

    /**
     * Update a webhook endpoint
     * Update a webhook endpoint
     * @param appId App ID (required)
     * @param endpointId Endpoint ID (required)
     * @param updateWebhook Request body (required)
     * @return ApiResponse&lt;Webhook&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Webhook> v1EndpointsUpdateWithHttpInfo(String appId, String endpointId, UpdateWebhook updateWebhook) throws ApiException {
        okhttp3.Call localVarCall = v1EndpointsUpdateValidateBeforeCall(appId, endpointId, updateWebhook, null);
        Type localVarReturnType = new TypeToken<Webhook>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update a webhook endpoint (asynchronously)
     * Update a webhook endpoint
     * @param appId App ID (required)
     * @param endpointId Endpoint ID (required)
     * @param updateWebhook Request body (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1EndpointsUpdateAsync(String appId, String endpointId, UpdateWebhook updateWebhook, final ApiCallback<Webhook> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1EndpointsUpdateValidateBeforeCall(appId, endpointId, updateWebhook, _callback);
        Type localVarReturnType = new TypeToken<Webhook>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
